# Generated by Django 3.1.7 on 2021-03-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addressbase',
            fields=[
                ('uprn', models.BigIntegerField(db_column='UPRN', primary_key=True, serialize=False)),
                ('full_address', models.TextField(blank=True, db_column='FULL_ADDRESS', null=True)),
                ('sub_building_name', models.TextField(blank=True, db_column='SUB_BUILDING_NAME', null=True)),
                ('building_name', models.TextField(blank=True, db_column='BUILDING_NAME', null=True)),
                ('building_number', models.TextField(blank=True, db_column='BUILDING_NUMBER', null=True)),
                ('thoroughfare', models.TextField(blank=True, db_column='THOROUGHFARE', null=True)),
                ('post_town', models.TextField(blank=True, db_column='POST_TOWN', null=True)),
                ('postcode', models.TextField(blank=True, db_column='POSTCODE', null=True)),
                ('logical_status', models.BigIntegerField(blank=True, db_column='LOGICAL_STATUS', null=True)),
                ('blpu_state', models.TextField(blank=True, db_column='BLPU_STATE', null=True)),
                ('x_coordinate', models.FloatField(blank=True, db_column='X_COORDINATE', null=True)),
                ('y_coordinate', models.FloatField(blank=True, db_column='Y_COORDINATE', null=True)),
                ('latitude', models.FloatField(blank=True, db_column='LATITUDE', null=True)),
                ('longitude', models.FloatField(blank=True, db_column='LONGITUDE', null=True)),
                ('country', models.TextField(blank=True, db_column='COUNTRY', null=True)),
                ('classification_code', models.TextField(blank=True, db_column='CLASSIFICATION_CODE', null=True)),
                ('usrn', models.TextField(blank=True, db_column='USRN', null=True)),
                ('street_description', models.TextField(blank=True, db_column='STREET_DESCRIPTION', null=True)),
                ('locality', models.TextField(blank=True, db_column='LOCALITY', null=True)),
                ('town_name', models.TextField(blank=True, db_column='TOWN_NAME', null=True)),
                ('administrative_area', models.TextField(blank=True, db_column='ADMINISTRATIVE_AREA', null=True)),
            ],
            options={
                'db_table': 'addressbase',
                'managed': False,
            },
        ),
    ]
