# Generated by Django 3.1.7 on 2021-03-24 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addressbase',
            options={'managed': True},
        ),
    ]
