name: Linting
on: [push, pull_request]
jobs:
  ruff:
    # uncomment the line before to disable this job if needed.
    # if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
