name: Type Checking

on: [push, pull_request, workflow_dispatch]

jobs:
  mypy:
    # uncomment the line before to disable this job if needed.
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Mypy
        uses: jpetrucciani/mypy-check@master
        with:
          path: "."
          mypy_flags:
            "--install-types --non-interactive --config-file pyproject.toml
            --ignore-missing-imports --strict"
          requirements_file: "requirements-dev.txt"
          python_version: "3.11"
